# Generated by Django 4.1.2 on 2022-10-27 23:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ejemplo', '0002_inventario'),
    ]

    operations = [
        migrations.CreateModel(
            name='Proveedores',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('empresa', models.CharField(max_length=10)),
                ('direccion', models.CharField(max_length=10)),
                ('fecha_de_alta', models.DateField()),
            ],
        ),
    ]
